imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    csrf_protection:
        enabled: false
doctrine:
    dbal:
        driver:  "pdo_sqlite"
        path:    "%kernel.cache_dir%/db.sqlite"
        charset: "UTF8"
        host:    '%database_host%'
        dbname:  '%database_name%_test'
web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true