_riverway_cms:
    resource: '@RiverwayCmsCoreBundle/Resources/config/routing.yml'

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"