security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    firewalls:
       dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
       main:
          pattern: ^/
          provider: in_memory
          form_login:
            login_path: login
            check_path: login
          logout:       true
          anonymous:    true
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
