security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin }

    firewalls:
       dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
       main:
          pattern: ^/
          form_login:
              provider: in_memory
              always_use_default_target_path: true
              default_target_path:  _redirect_after_login
          logout:       true
          anonymous:    true