Riverway\Cms\CoreBundle\Entity\Sidebar:
    type: entity
    table: sidebar
    repositoryClass: Riverway\Cms\CoreBundle\Repository\SidebarRepository

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    oneToMany:
        widgets:
            targetEntity: Riverway\Cms\CoreBundle\Entity\Widget
            fetch: LAZY
            mappedBy: sidebar
            orphanRemoval: false
    lifecycleCallbacks: {  }
