Riverway\Cms\CoreBundle\Entity\Slider:
    type: entity
    table: slider
    repositoryClass: Riverway\Cms\CoreBundle\Repository\SliderRepository
    uniqueConstraints:
        UNIQ_23A0E66841CB122:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        display:
            type: integer
            nullable: false
            options:
                unsigned: false
        creator:
            type: string
            nullable: true
    lifecycleCallbacks:
        prePersist: [updatedTimestamps]
        preUpdate: [updatedTimestamps]
