Riverway\Cms\CoreBundle\Entity\SlideElementParameters:
    type: entity
    table: null
    repositoryClass: Riverway\Cms\CoreBundle\Repository\SlideElementParametersRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        text: SlideElementParameters
        button: SlideButtonElementParameters
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: string
            length: 255
            nullable: true
        textColor:
            type: string
            length: 255
            nullable: true
        marginLeft:
            type: string
            length: 255
            nullable: false
        width:
            type: string
            length: 255
            nullable: false
        url:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
