Riverway\Cms\CoreBundle\Entity\Tag:
    type: entity
    table: tag
    repositoryClass: Riverway\Cms\CoreBundle\Repository\TagRepository
    uniqueConstraints:
        UNIQ_389B7835E237E06:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
