<?php

namespace Riverway\Cms\CoreBundle\Repository;

/**
 * SlideElementParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideElementParametersRepository extends \Doctrine\ORM\EntityRepository
{
}
