<?php

namespace Riverway\Cms\CoreBundle\Repository;

use Riverway\Cms\CoreBundle\Entity\Tag;
use Doctrine\ORM\AbstractQuery;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findList(int $limit = 10, string $q): array
    {
        return $this->createQueryBuilder('t')
            ->addSelect('t.id, t.name as text')
            ->andWhere('t.name LIKE :q')
            ->setParameter('q', '%'.$q.'%')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
