<?php

namespace Riverway\Cms\CoreBundle\Repository;

use Riverway\Cms\CoreBundle\Entity\Category;
use Riverway\Cms\CoreBundle\Entity\Widget;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveWidget(Widget $entity)
    {
        $this->getEntityManager()->persist($entity);
    }
}
